export const CATEGORIES = [
  { id: 'chronograph', name: 'Chronographs', slug: 'chronograph', description: 'Precision timing masterpieces' },
  { id: 'dress', name: 'Dress Watches', slug: 'dress', description: 'Elegance for formal occasions' },
  { id: 'diver', name: 'Diver Watches', slug: 'diver', description: 'Built for the deep' },
  { id: 'tourbillon', name: 'Tourbillons', slug: 'tourbillon', description: 'Haute horology complications' },
  { id: 'gmt', name: 'GMT & Travel', slug: 'gmt', description: 'For the world traveler' },
  { id: 'ladies', name: 'Ladies Collection', slug: 'ladies', description: 'Refined timepieces for her' },
]

export const COLLECTIONS = [
  { id: 'heritage', name: 'Heritage', slug: 'heritage', tagline: 'Timeless traditions reimagined', image: 'https://images.unsplash.com/photo-1611353384046-8a02bac0f14d' },
  { id: 'obsidian', name: 'Obsidian Noir', slug: 'obsidian', tagline: 'Darkness. Refined.', image: 'https://images.unsplash.com/photo-1568154106189-717dc85b0a3b' },
  { id: 'celestial', name: 'Celestial', slug: 'celestial', tagline: 'Inspired by the cosmos', image: 'https://images.pexels.com/photos/37547216/pexels-photo-37547216.jpeg' },
]

const IMG = {
  a: 'https://images.unsplash.com/photo-1611353384046-8a02bac0f14d',
  b: 'https://images.unsplash.com/photo-1600003014637-ff82a275e191',
  c: 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6',
  d: 'https://images.unsplash.com/photo-1600003014608-c2ccc1570a65',
  e: 'https://images.unsplash.com/photo-1612771409641-b0478cab8b69',
  f: 'https://images.unsplash.com/photo-1568154106189-717dc85b0a3b',
  g: 'https://images.pexels.com/photos/380782/pexels-photo-380782.jpeg',
  h: 'https://images.unsplash.com/photo-1700647153994-aece6c354a54',
  i: 'https://images.pexels.com/photos/37547216/pexels-photo-37547216.jpeg',
}

export const PRODUCTS = [
  {
    _id: 'p001', slug: 'chronos-titanium', name: 'Chronos Titanium', tagline: 'The Pinnacle of Precision',
    price: 485000, compareAtPrice: 520000, currency: 'INR',
    category: 'chronograph', collection: 'heritage', brand: 'Auverra',
    images: [IMG.b, IMG.c, IMG.d, IMG.g],
    description: 'Forged from grade-5 titanium, the Chronos Titanium is a masterclass in modern chronograph design. Its in-house AV-C7 movement delivers 72 hours of power reserve, while the sapphire-crystal display case reveals the beating heart of Swiss precision.',
    features: ['In-house AV-C7 automatic movement', '72-hour power reserve', 'Grade-5 titanium case', 'Sapphire crystal (anti-reflective)', 'Water resistant 100m', 'Luminescent Super-LumiNova indices'],
    specs: { movement: 'Automatic AV-C7', case: '42mm Grade-5 Titanium', dial: 'Obsidian Sunburst', crystal: 'Sapphire', waterResistance: '100m', powerReserve: '72 hours', strap: 'Titanium bracelet with butterfly clasp', weight: '138g' },
    variants: {
      dial: [{ name: 'Obsidian Black', hex: '#0a0a0b' }, { name: 'Champagne Gold', hex: '#c9a961' }, { name: 'Slate Blue', hex: '#1e2a44' }],
      strap: [{ name: 'Titanium Bracelet' }, { name: 'Black Alligator Leather' }, { name: 'Nato Charcoal' }],
    },
    stock: 12, rating: 4.9, reviewCount: 87, featured: true, bestSeller: true, newArrival: false, limitedEdition: false, badges: ['Best Seller'],
  },
  {
    _id: 'p002', slug: 'aurora-rose-gold', name: 'Aurora Rose Gold', tagline: 'Warmth of Dawn Captured',
    price: 620000, compareAtPrice: null, currency: 'INR',
    category: 'dress', collection: 'heritage', brand: 'Auverra',
    images: [IMG.c, IMG.b, IMG.d],
    description: 'The Aurora Rose Gold embraces the warm glow of first light. Its 18k rose gold case houses a mother-of-pearl dial, framed by hand-applied indices. A dress watch worthy of the most refined wrist.',
    features: ['18k rose gold case', 'Mother-of-pearl dial', 'Automatic AV-D3 movement', '42-hour power reserve', 'Alligator leather strap', 'Deployment clasp'],
    specs: { movement: 'Automatic AV-D3', case: '39mm 18k Rose Gold', dial: 'Mother-of-Pearl', crystal: 'Sapphire (double AR)', waterResistance: '50m', powerReserve: '42 hours', strap: 'Black Alligator Leather', weight: '96g' },
    variants: {
      dial: [{ name: 'Mother-of-Pearl', hex: '#f5f0e8' }, { name: 'Ivory Enamel', hex: '#f3e9d2' }],
      strap: [{ name: 'Black Alligator' }, { name: 'Cognac Alligator' }],
    },
    stock: 6, rating: 4.8, reviewCount: 52, featured: true, bestSeller: true, newArrival: false, limitedEdition: false, badges: ['Handcrafted'],
  },
  {
    _id: 'p003', slug: 'obsidian-diver-300', name: 'Obsidian Diver 300', tagline: 'Descend Without Compromise',
    price: 395000, compareAtPrice: 425000, currency: 'INR',
    category: 'diver', collection: 'obsidian', brand: 'Auverra',
    images: [IMG.d, IMG.g, IMG.b],
    description: 'Engineered for depths that few dare to explore. The Obsidian Diver 300 features a unidirectional ceramic bezel, helium escape valve, and 300m water resistance. Built for the abyss, styled for the boardroom.',
    features: ['300m water resistance', 'Ceramic unidirectional bezel', 'Helium escape valve', 'ISO 6425 certified', 'Automatic AV-D5 movement', 'Screw-down crown'],
    specs: { movement: 'Automatic AV-D5', case: '43mm Stainless Steel DLC', dial: 'Deep Obsidian', crystal: 'Sapphire (3mm)', waterResistance: '300m', powerReserve: '60 hours', strap: 'Rubber tropic strap', weight: '178g' },
    variants: {
      dial: [{ name: 'Deep Obsidian', hex: '#0a0a0b' }, { name: 'Abyssal Blue', hex: '#0d1f3a' }],
      strap: [{ name: 'Rubber Tropic' }, { name: 'Steel Bracelet' }],
    },
    stock: 18, rating: 4.7, reviewCount: 143, featured: true, bestSeller: true, newArrival: true, limitedEdition: false, badges: ['New Arrival', 'ISO Certified'],
  },
  {
    _id: 'p004', slug: 'celeste-tourbillon', name: 'Céleste Tourbillon', tagline: 'Gravity, Defied',
    price: 1850000, compareAtPrice: null, currency: 'INR',
    category: 'tourbillon', collection: 'celestial', brand: 'Auverra',
    images: [IMG.f, IMG.b, IMG.i],
    description: 'A tourbillon suspended in a sapphire cage, visible from every angle. The Céleste represents the summit of Auverra haute horology — hand-finished, hand-assembled, and limited to 25 pieces worldwide.',
    features: ['Flying tourbillon complication', 'Hand-engraved skeleton bridge', 'Limited to 25 pieces', 'Sapphire caseback', '18k white gold', '80-hour power reserve'],
    specs: { movement: 'Manual AV-T1 Tourbillon', case: '41mm 18k White Gold', dial: 'Skeleton', crystal: 'Sapphire (front & back)', waterResistance: '30m', powerReserve: '80 hours', strap: 'Hand-stitched alligator', weight: '112g' },
    variants: { strap: [{ name: 'Midnight Alligator' }, { name: 'Burgundy Alligator' }] },
    stock: 3, rating: 5.0, reviewCount: 21, featured: true, bestSeller: false, newArrival: false, limitedEdition: true, badges: ['Limited Edition', '25 Pieces Only'],
  },
  {
    _id: 'p005', slug: 'regent-platinum', name: 'Regent Platinum', tagline: 'The Sovereign\'s Choice',
    price: 875000, compareAtPrice: null, currency: 'INR',
    category: 'dress', collection: 'heritage', brand: 'Auverra',
    images: [IMG.e, IMG.c, IMG.d],
    description: 'Solid 950 platinum. Understated. Weighty. Utterly authoritative. The Regent is what a serious watch collector wears when they have nothing to prove.',
    features: ['950 platinum case', 'Silvered opaline dial', 'Blued steel hands', 'AV-D1 automatic movement', '45-hour power reserve', 'Sapphire caseback'],
    specs: { movement: 'Automatic AV-D1', case: '40mm 950 Platinum', dial: 'Silvered Opaline', crystal: 'Sapphire', waterResistance: '50m', powerReserve: '45 hours', strap: 'Black alligator', weight: '148g' },
    variants: { dial: [{ name: 'Silvered Opaline', hex: '#e5e5ea' }, { name: 'Midnight Blue', hex: '#0d1f3a' }] },
    stock: 4, rating: 4.9, reviewCount: 38, featured: false, bestSeller: false, newArrival: false, limitedEdition: false, badges: [],
  },
  {
    _id: 'p006', slug: 'nocturne-skeleton', name: 'Nocturne Skeleton', tagline: 'Bare the Mechanism',
    price: 540000, compareAtPrice: 590000, currency: 'INR',
    category: 'chronograph', collection: 'obsidian', brand: 'Auverra',
    images: [IMG.f, IMG.b, IMG.d],
    description: 'Every gear, every wheel, every pinion — exposed. The Nocturne Skeleton celebrates the raw beauty of horological engineering with a fully open-worked dial.',
    features: ['Fully skeletonized movement', 'Hand-finished bridges', 'DLC-coated titanium case', '68-hour power reserve', 'Sapphire double-domed crystal', 'Rubber strap with steel deployant'],
    specs: { movement: 'Automatic AV-SK7', case: '42mm DLC Titanium', dial: 'Skeleton Open-Worked', crystal: 'Sapphire Double-Domed', waterResistance: '50m', powerReserve: '68 hours', strap: 'Black rubber', weight: '124g' },
    variants: { strap: [{ name: 'Black Rubber' }, { name: 'Titanium Bracelet' }] },
    stock: 9, rating: 4.8, reviewCount: 64, featured: true, bestSeller: false, newArrival: true, limitedEdition: false, badges: ['New Arrival'],
  },
  {
    _id: 'p007', slug: 'voyager-gmt', name: 'Voyager GMT', tagline: 'Two Time Zones, One Icon',
    price: 425000, compareAtPrice: null, currency: 'INR',
    category: 'gmt', collection: 'heritage', brand: 'Auverra',
    images: [IMG.g, IMG.b, IMG.c],
    description: 'The perfect companion for the modern voyager. Track two time zones with the distinctive Auverra GMT hand and 24-hour bezel. Steel construction, jet-set spirit.',
    features: ['True GMT complication', 'Bidirectional 24h ceramic bezel', 'Stainless steel case', 'AV-G4 automatic movement', '70-hour power reserve', 'Screw-down crown'],
    specs: { movement: 'Automatic AV-G4 GMT', case: '41mm Stainless Steel', dial: 'Sunburst Blue', crystal: 'Sapphire', waterResistance: '150m', powerReserve: '70 hours', strap: 'Steel oyster bracelet', weight: '164g' },
    variants: { dial: [{ name: 'Sunburst Blue', hex: '#1e2a44' }, { name: 'Black', hex: '#0a0a0b' }, { name: 'Green', hex: '#0f3626' }] },
    stock: 22, rating: 4.7, reviewCount: 91, featured: false, bestSeller: true, newArrival: false, limitedEdition: false, badges: ['Best Seller'],
  },
  {
    _id: 'p008', slug: 'empress-diamond', name: 'Empress Diamond', tagline: 'Reign in Radiance',
    price: 780000, compareAtPrice: null, currency: 'INR',
    category: 'ladies', collection: 'celestial', brand: 'Auverra',
    images: [IMG.h, IMG.c, IMG.e],
    description: 'Sixty-four hand-set VVS diamonds encircle a mother-of-pearl dial. The Empress is a jewel first, a timepiece second — and utterly essential either way.',
    features: ['64 VVS diamonds (1.2ct total)', '18k rose gold case', 'Mother-of-pearl dial', 'Diamond hour markers', 'Automatic AV-L2 movement', 'Satin strap with rose gold buckle'],
    specs: { movement: 'Automatic AV-L2', case: '34mm 18k Rose Gold + Diamonds', dial: 'Mother-of-Pearl', crystal: 'Sapphire', waterResistance: '30m', powerReserve: '40 hours', strap: 'Ivory satin', weight: '68g' },
    variants: { strap: [{ name: 'Ivory Satin' }, { name: 'Blush Satin' }, { name: 'Rose Gold Bracelet' }] },
    stock: 5, rating: 4.9, reviewCount: 43, featured: true, bestSeller: false, newArrival: false, limitedEdition: false, badges: ['Handcrafted'],
  },
  {
    _id: 'p009', slug: 'legacy-moonphase', name: 'Legacy Moonphase', tagline: 'The Sky, On Your Wrist',
    price: 990000, compareAtPrice: null, currency: 'INR',
    category: 'tourbillon', collection: 'celestial', brand: 'Auverra',
    images: [IMG.i, IMG.e, IMG.d],
    description: 'A hand-painted enamel moonphase display, accurate to one day every 122 years. The Legacy Moonphase is a celestial poem, told in gold and lapis.',
    features: ['Astronomical moonphase (122yr accuracy)', 'Grand feu enamel dial', '18k yellow gold', 'AV-M3 automatic movement', '55-hour power reserve', 'Hand-stitched alligator'],
    specs: { movement: 'Automatic AV-M3', case: '40mm 18k Yellow Gold', dial: 'Grand Feu Enamel', crystal: 'Sapphire', waterResistance: '30m', powerReserve: '55 hours', strap: 'Midnight blue alligator', weight: '106g' },
    variants: { strap: [{ name: 'Midnight Blue Alligator' }, { name: 'Black Alligator' }] },
    stock: 7, rating: 4.9, reviewCount: 29, featured: false, bestSeller: false, newArrival: true, limitedEdition: false, badges: ['New Arrival'],
  },
  {
    _id: 'p010', slug: 'meridian-chronograph', name: 'Meridian Chronograph', tagline: 'Time in Motion',
    price: 365000, compareAtPrice: 410000, currency: 'INR',
    category: 'chronograph', collection: 'heritage', brand: 'Auverra',
    images: [IMG.b, IMG.g, IMG.c],
    description: 'Panda dial. Column-wheel chronograph. Vintage racing spirit for the modern connoisseur. The Meridian is our love letter to motorsport heritage.',
    features: ['Column-wheel chronograph', 'Panda dial configuration', 'AV-C3 automatic movement', 'Tachymeter bezel', '60-hour power reserve', 'Steel case with polished bezel'],
    specs: { movement: 'Automatic AV-C3 Chronograph', case: '41mm Stainless Steel', dial: 'Panda (White/Black)', crystal: 'Sapphire (Box-shaped)', waterResistance: '100m', powerReserve: '60 hours', strap: 'Perforated racing leather', weight: '152g' },
    variants: {
      dial: [{ name: 'Panda White', hex: '#f3e9d2' }, { name: 'Reverse Panda Black', hex: '#0a0a0b' }],
      strap: [{ name: 'Racing Leather Black' }, { name: 'Steel Bracelet' }],
    },
    stock: 15, rating: 4.8, reviewCount: 108, featured: true, bestSeller: true, newArrival: false, limitedEdition: false, badges: ['Best Seller'],
  },
]

export const TESTIMONIALS = [
  { name: 'Arjun Mehta', title: 'Collector, Mumbai', text: 'The Céleste Tourbillon exceeded every expectation. Auverra’s craftsmanship rivals the very best from Geneva.', rating: 5 },
  { name: 'Priya Kapoor', title: 'Journalist, Delhi', text: 'Elegant, understated, and impeccably finished. My Aurora Rose Gold draws compliments daily.', rating: 5 },
  { name: 'Rajiv Sinha', title: 'Entrepreneur, Bangalore', text: 'Genuine haute horology at a fair price. The Obsidian Diver has been on my wrist for six months and I still discover new details.', rating: 5 },
  { name: 'Meera Iyer', title: 'Architect, Chennai', text: 'The Empress Diamond is a work of art. Extraordinary attention to detail — you can feel the human touch.', rating: 5 },
]
